print("What is your name")
user_name=input()
print("Hello,",user_name)
print ("How old are you")
user_age=input()
print("Your age is",user_age)
print("Where do you live")
user_city=input()
print("You live in",user_city)