print("Enter the first number: ")
a = int(input())
print("Enter the second number: ")
b = int(input())
print("A + B = ", a + b)
print("A - B = ", a + b)
print("A * B = ", a * b)
print("A / B = ", a / b)
print("A ** B = ", a ** b)
print("A // B = ", a // b)
print("A % B = ", a % b)


print("Also try the second option \U0001F600")
print("Enter the first number: ")
a = int(input())
print("Enter the second number: ")
b = int(input())
print(f"{b} + {b} = ", a + b)
print(f"{a} - {b} = ", a + b)
print(f"{a} * {b} = ", a * b)
print(f"{a} / {b} = ", a / b)
print(f"{a} ** {b} = ", a ** b)
print(f"{a} // {b} = ", a // b)
print(f"{a} % {b} = ", a % b)