A=int (input ('enter A '))
B=int (input ('enter B ')) 
print ('So A=', A,'and B=', B)
print ('sum (A+B)=,', A + B)
print ('subtraction (A-B) =', A-B)
print ('multiplication=(A*B)', A * B)
print ('division(A/B)=', A / B)
print ('raised to the power (A**B)=', A ** B)
print ('int division(A//B)=', A // B)
print ('remainder of the division(A%B)=', A % B)