# "A + B = "  ...
# "A - B = "   ...
# "A * B = "   ...
# "A / B = "   ...
# "A**B = "   ...
# "A//B = "   ...
# "A%B = "  ...

a = float(input("Enter you 1st number: "))
b = float(input("Enter you 2nd nimber: "))

print("a + b = ", a + b)
print("a - b = ", a - b)
print("a * b = ", a * b)
print("a / b = ", a / b)
print("a ** b = ", a ** b)
print("a // b = ", a // b)
print("a % b = ", a % b)


print('hello')