var1 = int(input("Number A = "))
var2 = int(input("Number B = "))

calculate1 = 'Sum A and B = ' + str(var1 + var2)
calculate2 = 'Difference A and B = ' + str(var1 - var2)
calculate3 = 'Multiplication A and B = ' + str(var1 * var2)
calculate4 = 'Division A and B = ' + str(var1 / var2)
calculate5 = 'Exponent A and B = ' + str(var1 ** var2)
calculate6 = 'Floor division A and B = ' + str(var1 // var2)
calculate7 = 'Modulus A and B = ' + str(var1 % var2)

print(calculate1)
print(calculate2)
print(calculate3)
print(calculate4)
print(calculate5)
print(calculate6)
print(calculate7)
